name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup/@v3
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Unit Tests
        run: pnpm test -- --watchAll=false
      - name: E2E Tests
        uses: cypress-io/github-action@v4
        with:
          start: pnpm start
          wait-on: 'http://localhost:3000'
